apiVersion: v1
kind: Service
metadata:
  name: alertmanager
spec:
  ports:
  - port: 9093
    targetPort: 9093
    nodePort: 31001 # Choose a suitable port within the range
  selector:
    app: alertmanager
  type: NodePort
