apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-rules
  namespace: default
data:
  cluster_alerts.yaml: |
    groups:
    - name: cluster_alerts
      rules:
      - alert: NodeNotReady
        expr: count(kube_node_status_condition{condition="Ready"}) != count(kube_node_info)
        for: 1m
        labels:
          severity: critical
        annotations:
          summary: "Node Not Ready"
          description: "Some nodes are not in ready state."

      - alert: PodFailed
        expr: count(kube_pod_status_phase{phase="Failed"}) > 0
        for: 1m
        labels:
          severity: critical
        annotations:
          summary: "Pod Failed"
          description: "Some pods have failed."

      - alert: HighCPUPressure
        expr: sum(kube_node_status_allocatable{resource="cpu"}) - sum(kube_pod_container_resource_requests_cpu_cores) < 0
        for: 1m
        labels:
          severity: warning
        annotations:
          summary: "High CPU Pressure"
          description: "CPU resources are under high pressure."

      - alert: DaemonSetPodsUnavailable
        expr: kube_daemonset_status_number_unavailable > 0
        for: 1m
        labels:
          severity: warning
        annotations:
          summary: "DaemonSet Pods Unavailable"
          description: "Some pods managed by DaemonSet are unavailable."

      - alert: ServiceCreationDelay
        expr: time() - kube_service_created > 600
        for: 1m
        labels:
          severity: warning
        annotations:
          summary: "Service Creation Delay"
          description: "Service creation is delayed for more than 10 minutes."

